services:
  llama:
    build: .
    container_name: llama-cpp
    restart: unless-stopped

    ports:
      - "8001:8080"

    volumes:
      - ./models:/models
      - llama_cache:/root/.cache/llama.cpp

    env_file:
      - .env

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  llama_cache: